steps:
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-east4-docker.pkg.dev/us-gcp-ame-its-842f4-npd-1/pop-stats/pop-stats:${COMMIT_SHA}', '-f', 'Dockerfile']
    dir: 'app'
  # Run api tests
  - name: 'us-east4-docker.pkg.dev/us-gcp-ame-its-842f4-npd-1/pop-stats/pop-stats:${COMMIT_SHA}'
    entrypoint: python
    args: ["api_tests.py"]
    dir: 'app'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/us-gcp-ame-its-842f4-npd-1/pop-stats/pop-stats:${COMMIT_SHA}']
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline", "pop-stats-pipeline",
        "--region", "us-east4",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "pop-stats=us-east4-docker.pkg.dev/us-gcp-ame-its-842f4-npd-1/pop-stats/pop-stats:${COMMIT_SHA}"
      ]
images:
- us-east4-docker.pkg.dev/us-gcp-ame-its-842f4-npd-1/pop-stats/pop-stats:${COMMIT_SHA}
options:
  requestedVerifyOption: VERIFIED
logsBucket: gs://my-cicd-demo-logs-bucket-olive
