apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging
   profiles:
   - staging
 - targetId: prod
   profiles:
   - prod

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
anthosCluster:
  membership: projects/us-gcp-ame-its-842f4-npd-1/locations/global/memberships/m2c-process
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/us-gcp-ame-its-842f4-npd-1/locations/us-east4/workerPools/my-private-pool
  serviceAccount: cloud-deploy-ci-cd-pipeline@us-gcp-ame-its-842f4-npd-1.iam.gserviceaccount.com
  
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging cluster
anthosCluster:
  membership: projects/us-gcp-ame-its-842f4-npd-1/locations/global/memberships/m2c-process
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/us-gcp-ame-its-842f4-npd-1/locations/us-east4/workerPools/my-private-pool
  serviceAccount: cloud-deploy-ci-cd-pipeline@us-gcp-ame-its-842f4-npd-1.iam.gserviceaccount.com


---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
anthosCluster:
  membership: projects/us-gcp-ame-its-842f4-npd-1/locations/global/memberships/m2c-process
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/us-gcp-ame-its-842f4-npd-1/locations/us-east4/workerPools/my-private-pool
  serviceAccount: cloud-deploy-ci-cd-pipeline@us-gcp-ame-its-842f4-npd-1.iam.gserviceaccount.com
  
