apiVersion: v1
kind: Service
metadata:
  name: pop-stats
  namespace: advisory
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: pop-stats
  externalTrafficPolicy: Local


